"""Assemble a Workbench-compatible schema script, using only the Python standard library."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTS = [ROOT / '00_create_database.sql', *sorted((ROOT / 'migrations').glob('*.sql'))]


def main():
    header = (
        '-- GENERATED by scripts/build_bootstrap.py; edit numbered migrations instead.\n'
        '-- MySQL Workbench: open this file and Execute All on the intended local connection.\n'
        '-- Stop on errors. Initial installation only; no seed, DROP DATABASE or user grants.\n'
    )
    chunks = [header]
    for part in PARTS:
        chunks.append(f'\n-- BEGIN {part.relative_to(ROOT).as_posix()}\n')
        chunks.append(part.read_text(encoding='utf-8-sig').rstrip() + '\n')
    target = ROOT / 'bootstrap.sql'
    target.write_text(''.join(chunks), encoding='utf-8', newline='\n')
    print(f'Built {target.name} from {len(PARTS)} source files.')


if __name__ == '__main__':
    main()
