-- Migration 001: MVP schema. Apply once, to an empty project database.
-- DDL in MySQL commits implicitly. Stop on the first error; do not use --force.
USE aiworkforce_ecommerce;
SET NAMES utf8mb4;
SET SESSION time_zone = '+00:00';
SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE schema_migrations (
  version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  description VARCHAR(255) NOT NULL,
  applied_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (version)
) ENGINE=InnoDB;

CREATE TABLE tenants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  name VARCHAR(255) NOT NULL,
  default_currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'VND',
  timezone VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_tenants_code (code),
  CONSTRAINT ck_tenants_status CHECK (status IN ('ACTIVE','SUSPENDED')),
  CONSTRAINT ck_tenants_currency CHECK (default_currency REGEXP '^[A-Z]{3}$')
) ENGINE=InnoDB;

CREATE TABLE actors (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  identity_provider VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  external_subject VARCHAR(191) COLLATE utf8mb4_bin NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  actor_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_actors_tenant_id (tenant_id, id),
  UNIQUE KEY uq_actors_identity (tenant_id, identity_provider, external_subject),
  CONSTRAINT fk_actors_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT ck_actors_type CHECK (actor_type IN ('HUMAN','SERVICE')),
  CONSTRAINT ck_actors_status CHECK (status IN ('ACTIVE','DISABLED'))
) ENGINE=InnoDB;

CREATE TABLE actor_roles (
  tenant_id BIGINT UNSIGNED NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  role_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  granted_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (tenant_id, actor_id, role_code),
  CONSTRAINT fk_actor_roles_actor FOREIGN KEY (tenant_id, actor_id) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_actor_roles_grantor FOREIGN KEY (tenant_id, granted_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_actor_roles_code CHECK (role_code IN ('ADMIN','OPERATOR','APPROVER','ANALYST','AUDITOR','INTEGRATION'))
) ENGINE=InnoDB;

CREATE TABLE products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
  name VARCHAR(255) NOT NULL,
  unit_price DECIMAL(18,2) NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'VND',
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
  source_system VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MOCK',
  external_product_id VARCHAR(191) COLLATE utf8mb4_bin NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_products_tenant_id (tenant_id, id),
  UNIQUE KEY uq_products_sku (tenant_id, sku),
  UNIQUE KEY uq_products_external (tenant_id, source_system, external_product_id),
  CONSTRAINT fk_products_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_products_creator FOREIGN KEY (tenant_id, created_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_products_updater FOREIGN KEY (tenant_id, updated_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_products_price CHECK (unit_price >= 0),
  CONSTRAINT ck_products_currency CHECK (currency REGEXP '^[A-Z]{3}$'),
  CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
) ENGINE=InnoDB;

CREATE TABLE warehouses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
  source_system VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MOCK',
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_warehouses_tenant_id (tenant_id, id),
  UNIQUE KEY uq_warehouses_code (tenant_id, code),
  CONSTRAINT fk_warehouses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_warehouses_creator FOREIGN KEY (tenant_id, created_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_warehouses_updater FOREIGN KEY (tenant_id, updated_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_warehouses_status CHECK (status IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

CREATE TABLE actor_warehouse_scopes (
  tenant_id BIGINT UNSIGNED NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED NOT NULL,
  can_read BOOLEAN NOT NULL DEFAULT TRUE,
  can_write BOOLEAN NOT NULL DEFAULT FALSE,
  can_approve BOOLEAN NOT NULL DEFAULT FALSE,
  granted_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (tenant_id, actor_id, warehouse_id),
  CONSTRAINT fk_warehouse_scope_actor FOREIGN KEY (tenant_id, actor_id) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_warehouse_scope_warehouse FOREIGN KEY (tenant_id, warehouse_id) REFERENCES warehouses (tenant_id, id),
  CONSTRAINT fk_warehouse_scope_grantor FOREIGN KEY (tenant_id, granted_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_warehouse_scope_flags CHECK (can_read IN (0,1) AND can_write IN (0,1) AND can_approve IN (0,1)),
  CONSTRAINT ck_warehouse_scope_read CHECK ((can_write = 0 AND can_approve = 0) OR can_read = 1)
) ENGINE=InnoDB;

CREATE TABLE inventory (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  quantity_on_hand BIGINT NOT NULL DEFAULT 0,
  quantity_reserved BIGINT NOT NULL DEFAULT 0,
  quantity_available BIGINT GENERATED ALWAYS AS (quantity_on_hand - quantity_reserved) STORED,
  reorder_point BIGINT NOT NULL DEFAULT 0,
  version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_system VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MOCK',
  last_synced_at TIMESTAMP(6) NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_inventory_tenant_id (tenant_id, id),
  UNIQUE KEY uq_inventory_stock (tenant_id, warehouse_id, product_id),
  KEY ix_inventory_product (tenant_id, product_id),
  CONSTRAINT fk_inventory_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_inventory_warehouse FOREIGN KEY (tenant_id, warehouse_id) REFERENCES warehouses (tenant_id, id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (tenant_id, product_id) REFERENCES products (tenant_id, id),
  CONSTRAINT fk_inventory_creator FOREIGN KEY (tenant_id, created_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_inventory_updater FOREIGN KEY (tenant_id, updated_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_inventory_nonnegative CHECK (quantity_on_hand >= 0 AND quantity_reserved >= 0 AND reorder_point >= 0),
  CONSTRAINT ck_inventory_reserved CHECK (quantity_reserved <= quantity_on_hand)
) ENGINE=InnoDB;

CREATE TABLE orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  order_number VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
  customer_ref VARCHAR(191) COLLATE utf8mb4_bin NULL COMMENT 'Opaque source reference; no customer PII/profile in MVP',
  source_system VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MOCK',
  external_order_id VARCHAR(191) COLLATE utf8mb4_bin NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DRAFT',
  payment_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UNPAID',
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'VND',
  subtotal_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  shipping_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(18,2) GENERATED ALWAYS AS (subtotal_amount - discount_amount + tax_amount + shipping_amount) STORED,
  refunded_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  placed_at TIMESTAMP(6) NULL,
  paid_at TIMESTAMP(6) NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_tenant_id (tenant_id, id),
  UNIQUE KEY uq_orders_number (tenant_id, order_number),
  UNIQUE KEY uq_orders_external (tenant_id, source_system, external_order_id),
  KEY ix_orders_customer (tenant_id, customer_ref, placed_at),
  KEY ix_orders_paid (tenant_id, paid_at, currency),
  KEY ix_orders_status (tenant_id, status, placed_at),
  CONSTRAINT fk_orders_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_orders_creator FOREIGN KEY (tenant_id, created_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_orders_updater FOREIGN KEY (tenant_id, updated_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_orders_status CHECK (status IN ('DRAFT','PLACED','CONFIRMED','FULFILLED','COMPLETED','CANCELLED')),
  CONSTRAINT ck_orders_payment CHECK (payment_status IN ('UNPAID','PAID','PARTIALLY_REFUNDED','REFUNDED')),
  CONSTRAINT ck_orders_currency CHECK (currency REGEXP '^[A-Z]{3}$'),
  CONSTRAINT ck_orders_amounts CHECK (subtotal_amount >= 0 AND discount_amount >= 0 AND discount_amount <= subtotal_amount AND tax_amount >= 0 AND shipping_amount >= 0 AND refunded_amount >= 0 AND refunded_amount <= total_amount),
  CONSTRAINT ck_orders_paid_at CHECK ((payment_status = 'UNPAID' AND paid_at IS NULL AND refunded_amount = 0) OR (payment_status <> 'UNPAID' AND paid_at IS NOT NULL)),
  CONSTRAINT ck_orders_refunds CHECK ((payment_status IN ('UNPAID','PAID') AND refunded_amount = 0) OR (payment_status = 'PARTIALLY_REFUNDED' AND refunded_amount > 0 AND refunded_amount < total_amount) OR (payment_status = 'REFUNDED' AND refunded_amount = total_amount))
) ENGINE=InnoDB;

CREATE TABLE order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  line_number SMALLINT UNSIGNED NOT NULL,
  sku_snapshot VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
  name_snapshot VARCHAR(255) NOT NULL,
  quantity BIGINT NOT NULL,
  unit_price DECIMAL(18,2) NOT NULL,
  discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  line_subtotal DECIMAL(18,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
  line_total DECIMAL(18,2) GENERATED ALWAYS AS (quantity * unit_price - discount_amount + tax_amount) STORED,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_order_items_tenant_id (tenant_id, id),
  UNIQUE KEY uq_order_items_line (tenant_id, order_id, line_number),
  KEY ix_order_items_product (tenant_id, product_id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (tenant_id, order_id) REFERENCES orders (tenant_id, id),
  CONSTRAINT fk_order_items_product FOREIGN KEY (tenant_id, product_id) REFERENCES products (tenant_id, id),
  CONSTRAINT ck_order_items_quantity CHECK (quantity > 0 AND line_number > 0),
  CONSTRAINT ck_order_items_amounts CHECK (unit_price >= 0 AND discount_amount >= 0 AND discount_amount <= quantity * unit_price AND tax_amount >= 0)
) ENGINE=InnoDB;

CREATE TABLE workflow_runs (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  requested_by BIGINT UNSIGNED NOT NULL,
  workflow_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CREATED',
  current_step VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  plan_version INT UNSIGNED NOT NULL DEFAULT 1,
  state_version INT UNSIGNED NOT NULL DEFAULT 1,
  state_json JSON NOT NULL,
  result_json JSON NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  failure_reason VARCHAR(1000) NULL COMMENT 'Redacted summary only',
  started_at TIMESTAMP(6) NULL,
  finished_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_workflows_tenant_id (tenant_id, id),
  KEY ix_workflows_queue (tenant_id, status, created_at),
  KEY ix_workflows_actor (tenant_id, requested_by, created_at),
  CONSTRAINT fk_workflows_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_workflows_requester FOREIGN KEY (tenant_id, requested_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_workflows_status CHECK (status IN ('CREATED','PLANNING','RUNNING','WAITING_FOR_APPROVAL','VALIDATING','EXECUTING_ACTION','COMPLETED','PARTIALLY_COMPLETED','FAILED','CANCELLED','EXPIRED','NEEDS_REVIEW')),
  CONSTRAINT ck_workflows_versions CHECK (plan_version > 0 AND state_version > 0),
  CONSTRAINT ck_workflows_terminal CHECK ((status IN ('COMPLETED','PARTIALLY_COMPLETED','FAILED','CANCELLED','EXPIRED') AND finished_at IS NOT NULL) OR (status NOT IN ('COMPLETED','PARTIALLY_COMPLETED','FAILED','CANCELLED','EXPIRED') AND finished_at IS NULL))
) ENGINE=InnoDB;

CREATE TABLE workflow_checkpoints (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  workflow_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  checkpoint_sequence BIGINT UNSIGNED NOT NULL,
  schema_version INT UNSIGNED NOT NULL,
  checkpoint_json JSON NOT NULL COMMENT 'Generic snapshot; LangGraph adapter must be implemented separately',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_checkpoints_sequence (tenant_id, workflow_id, checkpoint_sequence),
  CONSTRAINT fk_checkpoints_workflow FOREIGN KEY (tenant_id, workflow_id) REFERENCES workflow_runs (tenant_id, id),
  CONSTRAINT ck_checkpoints_versions CHECK (checkpoint_sequence > 0 AND schema_version > 0)
) ENGINE=InnoDB;

CREATE TABLE approval_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  workflow_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  requested_by BIGINT UNSIGNED NOT NULL,
  action_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  action_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payload JSON NOT NULL COMMENT 'Redacted canonical action payload; hash computed by backend',
  payload_hash BINARY(32) NOT NULL,
  resource_versions JSON NOT NULL,
  risk_level VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  policy_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  risk_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PENDING',
  decided_by BIGINT UNSIGNED NULL,
  decision_reason VARCHAR(1000) NULL,
  decided_at TIMESTAMP(6) NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  executed_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_approvals_tenant_id (tenant_id, id),
  UNIQUE KEY uq_approvals_workflow_binding (tenant_id, id, workflow_id),
  UNIQUE KEY uq_approvals_action (tenant_id, workflow_id, action_key),
  KEY ix_approvals_queue (tenant_id, status, expires_at),
  CONSTRAINT fk_approvals_workflow FOREIGN KEY (tenant_id, workflow_id) REFERENCES workflow_runs (tenant_id, id),
  CONSTRAINT fk_approvals_requester FOREIGN KEY (tenant_id, requested_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_approvals_decider FOREIGN KEY (tenant_id, decided_by) REFERENCES actors (tenant_id, id),
  CONSTRAINT ck_approvals_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  CONSTRAINT ck_approvals_status CHECK (status IN ('PENDING','APPROVED','REJECTED','EXPIRED','CANCELLED','EXECUTED')),
  CONSTRAINT ck_approvals_decision CHECK ((decided_by IS NULL AND decided_at IS NULL) OR (decided_by IS NOT NULL AND decided_at IS NOT NULL)),
  CONSTRAINT ck_approvals_decided_status CHECK (status NOT IN ('APPROVED','REJECTED','EXECUTED') OR (decided_by IS NOT NULL AND decided_at IS NOT NULL)),
  CONSTRAINT ck_approvals_pending CHECK (status <> 'PENDING' OR (decided_by IS NULL AND decided_at IS NULL)),
  CONSTRAINT ck_approvals_execution CHECK ((status = 'EXECUTED' AND executed_at IS NOT NULL) OR (status <> 'EXECUTED' AND executed_at IS NULL)),
  CONSTRAINT ck_approvals_rejection CHECK (status <> 'REJECTED' OR (decision_reason IS NOT NULL AND CHAR_LENGTH(TRIM(decision_reason)) > 0)),
  CONSTRAINT ck_approvals_expiry CHECK (expires_at > created_at)
) ENGINE=InnoDB;

CREATE TABLE idempotency_keys (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  workflow_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  approval_id BIGINT UNSIGNED NULL,
  operation_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  idempotency_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payload_hash BINARY(32) NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'IN_PROGRESS',
  response_snapshot JSON NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_owner VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_expires_at TIMESTAMP(6) NULL,
  completed_at TIMESTAMP(6) NULL,
  expires_at TIMESTAMP(6) NULL COMMENT 'Retention horizon; never clean up an unresolved operation',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_idempotency_tenant_id (tenant_id, id),
  UNIQUE KEY uq_idempotency_identity (tenant_id, actor_id, operation_name, idempotency_key),
  UNIQUE KEY uq_idempotency_action_binding (tenant_id, id, workflow_id, actor_id),
  KEY ix_idempotency_recovery (tenant_id, status, lease_expires_at),
  KEY ix_idempotency_cleanup (status, expires_at),
  CONSTRAINT fk_idempotency_actor FOREIGN KEY (tenant_id, actor_id) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_idempotency_workflow FOREIGN KEY (tenant_id, workflow_id) REFERENCES workflow_runs (tenant_id, id),
  CONSTRAINT fk_idempotency_approval FOREIGN KEY (tenant_id, approval_id, workflow_id) REFERENCES approval_requests (tenant_id, id, workflow_id),
  CONSTRAINT ck_idempotency_status CHECK (status IN ('IN_PROGRESS','COMPLETED','FAILED','NEEDS_REVIEW')),
  CONSTRAINT ck_idempotency_lease CHECK ((lease_owner IS NULL AND lease_expires_at IS NULL) OR (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)),
  CONSTRAINT ck_idempotency_completion CHECK ((status = 'COMPLETED' AND completed_at IS NOT NULL AND response_snapshot IS NOT NULL) OR (status = 'FAILED' AND completed_at IS NOT NULL AND error_code IS NOT NULL) OR (status IN ('IN_PROGRESS','NEEDS_REVIEW') AND completed_at IS NULL AND expires_at IS NULL)),
  CONSTRAINT ck_idempotency_retention CHECK (expires_at IS NULL OR (completed_at IS NOT NULL AND expires_at > completed_at))
) ENGINE=InnoDB;

CREATE TABLE audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  workflow_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  idempotency_id BIGINT UNSIGNED NULL,
  approval_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  agent_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  tool_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  tool_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  outcome VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  risk_level VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  policy_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  risk_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payload_hash BINARY(32) NOT NULL,
  redacted_input JSON NULL,
  redacted_output JSON NULL,
  duration_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cost_amount DECIMAL(18,8) NOT NULL DEFAULT 0,
  cost_currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'USD',
  chain_sequence BIGINT UNSIGNED NULL,
  prev_hash BINARY(32) NULL,
  record_hash BINARY(32) NULL COMMENT 'Reserved for verified hash-chain writer in Phase 5',
  occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_audit_tenant_id (tenant_id, id),
  UNIQUE KEY uq_audit_action_binding (tenant_id, id, workflow_id, actor_id, idempotency_id),
  UNIQUE KEY uq_audit_chain_sequence (tenant_id, chain_sequence),
  KEY ix_audit_workflow (tenant_id, workflow_id, occurred_at),
  KEY ix_audit_actor (tenant_id, actor_id, occurred_at),
  CONSTRAINT fk_audit_workflow FOREIGN KEY (tenant_id, workflow_id) REFERENCES workflow_runs (tenant_id, id),
  CONSTRAINT fk_audit_actor FOREIGN KEY (tenant_id, actor_id) REFERENCES actors (tenant_id, id),
  CONSTRAINT fk_audit_idempotency FOREIGN KEY (tenant_id, idempotency_id, workflow_id, actor_id) REFERENCES idempotency_keys (tenant_id, id, workflow_id, actor_id),
  CONSTRAINT fk_audit_approval FOREIGN KEY (tenant_id, approval_id, workflow_id) REFERENCES approval_requests (tenant_id, id, workflow_id),
  CONSTRAINT ck_audit_outcome CHECK (outcome IN ('SUCCESS','DENIED','FAILED','PROPOSED','UNKNOWN')),
  CONSTRAINT ck_audit_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  CONSTRAINT ck_audit_cost CHECK (cost_amount >= 0 AND cost_currency REGEXP '^[A-Z]{3}$'),
  CONSTRAINT ck_audit_chain_fields CHECK ((record_hash IS NULL AND prev_hash IS NULL AND chain_sequence IS NULL) OR (record_hash IS NOT NULL AND chain_sequence IS NOT NULL AND chain_sequence > 0))
) ENGINE=InnoDB;

CREATE TABLE inventory_movements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  inventory_id BIGINT UNSIGNED NOT NULL,
  workflow_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  idempotency_id BIGINT UNSIGNED NOT NULL,
  audit_event_id BIGINT UNSIGNED NOT NULL,
  action_line SMALLINT UNSIGNED NOT NULL,
  quantity_delta BIGINT NOT NULL,
  reserved_delta BIGINT NOT NULL DEFAULT 0,
  balance_before BIGINT NOT NULL,
  balance_after BIGINT NOT NULL,
  reserved_before BIGINT NOT NULL DEFAULT 0,
  reserved_after BIGINT NOT NULL DEFAULT 0,
  inventory_version_after BIGINT UNSIGNED NOT NULL,
  reason_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reference_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reference_id VARCHAR(191) COLLATE utf8mb4_bin NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_movements_tenant_id (tenant_id, id),
  UNIQUE KEY uq_movements_action_line (tenant_id, idempotency_id, action_line),
  UNIQUE KEY uq_movements_inventory_version (tenant_id, inventory_id, inventory_version_after),
  KEY ix_movements_inventory (tenant_id, inventory_id, created_at),
  KEY ix_movements_workflow (tenant_id, workflow_id),
  CONSTRAINT fk_movements_inventory FOREIGN KEY (tenant_id, inventory_id) REFERENCES inventory (tenant_id, id),
  CONSTRAINT fk_movements_idempotency FOREIGN KEY (tenant_id, idempotency_id, workflow_id, actor_id) REFERENCES idempotency_keys (tenant_id, id, workflow_id, actor_id),
  CONSTRAINT fk_movements_audit FOREIGN KEY (tenant_id, audit_event_id, workflow_id, actor_id, idempotency_id) REFERENCES audit_events (tenant_id, id, workflow_id, actor_id, idempotency_id),
  CONSTRAINT ck_movements_delta CHECK (quantity_delta <> 0 OR reserved_delta <> 0),
  CONSTRAINT ck_movements_balance CHECK (balance_before >= 0 AND balance_after >= 0 AND balance_after = balance_before + quantity_delta),
  CONSTRAINT ck_movements_reservation CHECK (reserved_before >= 0 AND reserved_after >= 0 AND reserved_after = reserved_before + reserved_delta AND reserved_before <= balance_before AND reserved_after <= balance_after),
  CONSTRAINT ck_movements_sequence CHECK (action_line > 0 AND inventory_version_after > 0),
  CONSTRAINT ck_movements_reason CHECK (reason_code IN ('OPENING_BALANCE','RESTOCK','SALE','RESERVE','RELEASE','CORRECTION','RECONCILIATION')),
  CONSTRAINT ck_movements_reference CHECK (reference_type IN ('MOCK','ORDER','MANUAL','AGENT','EXTERNAL'))
) ENGINE=InnoDB;

INSERT INTO schema_migrations (version, description)
VALUES ('001', 'MVP entities, tenant composite foreign keys, workflow and write-control contracts');
